"""create scoped investigation data model

Revision ID: 0001_scoped_model
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_scoped_model"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("auth_issuer", sa.String(length=512), nullable=False),
        sa.Column("auth_subject", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint(
            "auth_issuer", "auth_subject", name=op.f("uq_users_auth_issuer_auth_subject")
        ),
        schema="faultbrief",
    )
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        schema="faultbrief",
    )
    op.create_table(
        "customers",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["faultbrief.workspaces.id"],
            name=op.f("fk_customers_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_customers_id_workspace_id")),
        sa.UniqueConstraint(
            "workspace_id", "external_id", name=op.f("uq_customers_workspace_id_external_id")
        ),
        schema="faultbrief",
    )
    op.create_index(
        "ix_customers_workspace_created",
        "customers",
        ["workspace_id", "created_at", "id"],
        unique=False,
        schema="faultbrief",
    )
    op.create_table(
        "integrations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "demo",
                "logs",
                "runbooks",
                name="integration_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("secret_ref", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["faultbrief.workspaces.id"],
            name=op.f("fk_integrations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_integrations_id_workspace_id")),
        schema="faultbrief",
    )
    op.create_table(
        "memberships",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "support",
                "viewer",
                name="membership_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["faultbrief.users.id"], name=op.f("fk_memberships_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["faultbrief.workspaces.id"],
            name=op.f("fk_memberships_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "workspace_id", "user_id", name=op.f("uq_memberships_workspace_id_user_id")
        ),
        schema="faultbrief",
    )
    op.create_table(
        "investigations",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "inconclusive",
                "failed",
                name="investigation_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'queued' AND started_at IS NULL AND finished_at IS NULL) OR "
            "(state = 'running' AND started_at IS NOT NULL AND finished_at IS NULL) OR "
            "(state IN ('completed', 'inconclusive') AND started_at IS NOT NULL "
            "AND finished_at IS NOT NULL) OR (state = 'failed' AND finished_at IS NOT NULL)",
            name=op.f("ck_investigations_state_timestamps"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_investigations_timestamp_order"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "workspace_id"],
            ["faultbrief.customers.id", "faultbrief.customers.workspace_id"],
            name=op.f("fk_investigations_customer_id_workspace_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "created_by_user_id"],
            ["faultbrief.memberships.workspace_id", "faultbrief.memberships.user_id"],
            name=op.f("fk_investigations_workspace_id_created_by_user_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["faultbrief.workspaces.id"],
            name=op.f("fk_investigations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
        sa.UniqueConstraint("id", "workspace_id", name=op.f("uq_investigations_id_workspace_id")),
        schema="faultbrief",
    )
    op.create_index(
        "ix_investigations_workspace_created",
        "investigations",
        ["workspace_id", "created_at", "id"],
        unique=False,
        schema="faultbrief",
    )
    op.create_table(
        "jobs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="job_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= max_attempts AND max_attempts > 0",
            name=op.f("ck_jobs_attempt_limits"),
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id", "workspace_id"],
            ["faultbrief.investigations.id", "faultbrief.investigations.workspace_id"],
            name=op.f("fk_jobs_investigation_id_workspace_id_investigations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "id",
            "investigation_id",
            "workspace_id",
            name=op.f("uq_jobs_id_investigation_id_workspace_id"),
        ),
        sa.UniqueConstraint("investigation_id", name=op.f("uq_jobs_investigation_id")),
        schema="faultbrief",
    )
    op.create_index(
        "ix_jobs_state_available",
        "jobs",
        ["state", "available_at"],
        unique=False,
        schema="faultbrief",
    )
    op.create_table(
        "reports",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("suggested_team", sa.String(length=80), nullable=True),
        sa.Column(
            "limitations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_reports_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id", "workspace_id"],
            ["faultbrief.investigations.id", "faultbrief.investigations.workspace_id"],
            name=op.f("fk_reports_investigation_id_workspace_id_investigations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "id",
            "investigation_id",
            "workspace_id",
            name=op.f("uq_reports_id_investigation_id_workspace_id"),
        ),
        sa.UniqueConstraint("investigation_id", name=op.f("uq_reports_investigation_id")),
        schema="faultbrief",
    )
    op.create_table(
        "feedback",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "rating",
            sa.Enum(
                "helpful",
                "incorrect",
                "incomplete",
                name="feedback_rating",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "investigation_id", "workspace_id"],
            [
                "faultbrief.reports.id",
                "faultbrief.reports.investigation_id",
                "faultbrief.reports.workspace_id",
            ],
            name=op.f("fk_feedback_report_id_investigation_id_workspace_id_reports"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "user_id"],
            ["faultbrief.memberships.workspace_id", "faultbrief.memberships.user_id"],
            name=op.f("fk_feedback_workspace_id_user_id_memberships"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("report_id", "user_id", name=op.f("uq_feedback_report_id_user_id")),
        schema="faultbrief",
    )
    op.create_table(
        "tool_calls",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=True),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "running",
                "completed",
                "failed",
                name="tool_call_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("read_only", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "arguments_redacted",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("read_only = true", name=op.f("ck_tool_calls_read_only_only")),
        sa.ForeignKeyConstraint(
            ["integration_id", "workspace_id"],
            ["faultbrief.integrations.id", "faultbrief.integrations.workspace_id"],
            name=op.f("fk_tool_calls_integration_id_workspace_id_integrations"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "investigation_id", "workspace_id"],
            [
                "faultbrief.jobs.id",
                "faultbrief.jobs.investigation_id",
                "faultbrief.jobs.workspace_id",
            ],
            name=op.f("fk_tool_calls_job_id_investigation_id_workspace_id_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint(
            "id",
            "investigation_id",
            "workspace_id",
            name=op.f("uq_tool_calls_id_investigation_id_workspace_id"),
        ),
        schema="faultbrief",
    )
    op.create_table(
        "evidence",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "log",
                "config",
                "health",
                "runbook",
                name="evidence_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source_ref", sa.String(length=512), nullable=False),
        sa.Column("source_version", sa.String(length=128), nullable=True),
        sa.Column("excerpt_redacted", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id", "workspace_id"],
            ["faultbrief.investigations.id", "faultbrief.investigations.workspace_id"],
            name=op.f("fk_evidence_investigation_id_workspace_id_investigations"),
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id", "investigation_id", "workspace_id"],
            [
                "faultbrief.tool_calls.id",
                "faultbrief.tool_calls.investigation_id",
                "faultbrief.tool_calls.workspace_id",
            ],
            name=op.f("fk_evidence_tool_call_id_investigation_id_workspace_id_tool_calls"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "id",
            "investigation_id",
            "workspace_id",
            name=op.f("uq_evidence_id_investigation_id_workspace_id"),
        ),
        schema="faultbrief",
    )
    op.create_table(
        "report_citations",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("quote", sa.String(length=800), nullable=True),
        sa.ForeignKeyConstraint(
            ["evidence_id", "investigation_id", "workspace_id"],
            [
                "faultbrief.evidence.id",
                "faultbrief.evidence.investigation_id",
                "faultbrief.evidence.workspace_id",
            ],
            name=op.f("fk_report_citations_evidence_id_investigation_id_workspace_id_evidence"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "investigation_id", "workspace_id"],
            [
                "faultbrief.reports.id",
                "faultbrief.reports.investigation_id",
                "faultbrief.reports.workspace_id",
            ],
            name=op.f("fk_report_citations_report_id_investigation_id_workspace_id_reports"),
        ),
        sa.PrimaryKeyConstraint("report_id", "evidence_id", name=op.f("pk_report_citations")),
        schema="faultbrief",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_citations", schema="faultbrief")
    op.drop_table("evidence", schema="faultbrief")
    op.drop_table("tool_calls", schema="faultbrief")
    op.drop_table("feedback", schema="faultbrief")
    op.drop_table("reports", schema="faultbrief")
    op.drop_index("ix_jobs_state_available", table_name="jobs", schema="faultbrief")
    op.drop_table("jobs", schema="faultbrief")
    op.drop_index(
        "ix_investigations_workspace_created", table_name="investigations", schema="faultbrief"
    )
    op.drop_table("investigations", schema="faultbrief")
    op.drop_table("memberships", schema="faultbrief")
    op.drop_table("integrations", schema="faultbrief")
    op.drop_index("ix_customers_workspace_created", table_name="customers", schema="faultbrief")
    op.drop_table("customers", schema="faultbrief")
    op.drop_table("workspaces", schema="faultbrief")
    op.drop_table("users", schema="faultbrief")
    # ### end Alembic commands ###
